# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 13:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180214_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 13, 51, 40, 446000, tzinfo=utc)),
        ),
    ]
